/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import org.springframework.stereotype.Component;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jpaDAO.CustomerJpaDao;
import jpaDAO.GenericJpaDao;
import jpaDAO.ProductJpaDao;
import jpaDAO.RentalItemJpaDao;
import models.Customer;
import models.Product;
import models.RentalItem;
import wypozyczalniefilmow.FilmRow;


/**
 *
 * @author Rozkurwozaur
 */

@Component
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    private boolean admin;
    private long idKonta;
    private String nazwaKonta;
    public Okno() {
        initComponents();
        this.admin=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JLayeredPane();
        loginField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        zalogujButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rejestracjaButton = new javax.swing.JButton();
        ZalogujSieLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JLayeredPane();
        tabPanel = new javax.swing.JTabbedPane();
        przegladajTab = new javax.swing.JPanel();
        szukajButton = new javax.swing.JButton();
        przegladajScrollPane = new javax.swing.JScrollPane();
        przegladajPanel = new javax.swing.JPanel();
        szukajTextField = new javax.swing.JTextField();
        zobaczWszystkieButton = new javax.swing.JButton();
        wypozyczButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zarezerwujButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idRezerText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        dodajTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cenaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tytulTextField = new javax.swing.JTextField();
        dodajButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idEditText = new javax.swing.JTextField();
        titleEditText = new javax.swing.JTextField();
        priceEditText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idDelete = new javax.swing.JTextField();
        usunButton = new javax.swing.JButton();
        zwrocButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kontoTab = new javax.swing.JPanel();
        nazwaKontaLabel = new javax.swing.JLabel();
        nazwaKontaDB = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        twojeRezerwacjeLabel = new javax.swing.JLabel();
        wylogujButton = new javax.swing.JButton();
        odswiezButton = new javax.swing.JButton();
        anulujRezButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        twojeRezerwacjeText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginField.setForeground(new java.awt.Color(204, 204, 204));
        loginField.setText("Nazwa użytkownika");
        loginField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginFieldMouseClicked(evt);
            }
        });

        loginLabel.setText("Login:");

        passwordLabel.setText("Hasło:");

        zalogujButton.setText("Zaloguj");
        zalogujButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zalogujButtonMouseClicked(evt);
            }
        });
        zalogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nie masz konta? Zarejestruj");

        rejestracjaButton.setText("Rejestracja");
        rejestracjaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejestracjaButtonMouseClicked(evt);
            }
        });

        ZalogujSieLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ZalogujSieLabel.setText("Logowanie");

        loginPanel.setLayer(loginField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(loginLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(zalogujButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(rejestracjaButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(ZalogujSieLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zalogujButton)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(passwordField)))
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(318, 318, 318))))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(ZalogujSieLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(rejestracjaButton)))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(ZalogujSieLabel)
                .addGap(52, 52, 52)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(zalogujButton)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rejestracjaButton)
                .addGap(87, 87, 87))
        );

        tabPanel.setToolTipText("");
        tabPanel.setName(""); // NOI18N
        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        szukajButton.setText("Szukaj");
        szukajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szukajButtonMouseClicked(evt);
            }
        });

        przegladajScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));

        javax.swing.GroupLayout przegladajPanelLayout = new javax.swing.GroupLayout(przegladajPanel);
        przegladajPanel.setLayout(przegladajPanelLayout);
        przegladajPanelLayout.setHorizontalGroup(
            przegladajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        przegladajPanelLayout.setVerticalGroup(
            przegladajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        przegladajScrollPane.setViewportView(przegladajPanel);

        zobaczWszystkieButton.setText("Zobacz wszystkie");
        zobaczWszystkieButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zobaczWszystkieButtonMouseClicked(evt);
            }
        });

        wypozyczButton.setText("Wypożycz");
        wypozyczButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wypozyczButtonMouseClicked(evt);
            }
        });

        jLabel8.setText("Id:");

        zarezerwujButton.setText("Zarezerwuj");
        zarezerwujButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zarezerwujButtonMouseClicked(evt);
            }
        });

        jLabel10.setText("Id:");

        jLabel11.setText("Data:");

        javax.swing.GroupLayout przegladajTabLayout = new javax.swing.GroupLayout(przegladajTab);
        przegladajTab.setLayout(przegladajTabLayout);
        przegladajTabLayout.setHorizontalGroup(
            przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(przegladajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(przegladajTabLayout.createSequentialGroup()
                        .addComponent(zobaczWszystkieButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(szukajButton))
                    .addComponent(przegladajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, przegladajTabLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idRezerText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(zarezerwujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wypozyczButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        przegladajTabLayout.setVerticalGroup(
            przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(przegladajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szukajButton)
                    .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zobaczWszystkieButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(przegladajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wypozyczButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(zarezerwujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(idRezerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabPanel.addTab("                                                      Przeglądaj                                                       ", przegladajTab);

        dodajTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajTabMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N
        jPanel1.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Dodaj Film");

        jLabel5.setText("Tytuł:");

        jLabel6.setText("Cena:");

        dodajButton.setText("Dodaj");
        dodajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajButtonMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Edytuj Film");

        jLabel12.setText("id:");

        jLabel13.setText("Tytuł:");

        jLabel14.setText("Cena:");

        updateButton.setText("Uaktualnij");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Usuń / Zwróć Film");

        jLabel7.setText("id:");

        usunButton.setText("Usuń");
        usunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usunButtonMouseClicked(evt);
            }
        });

        zwrocButton.setText("Zwróć");
        zwrocButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zwrocButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tytulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodajButton))
                        .addGap(81, 81, 81)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addComponent(jLabel14))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEditText)
                            .addComponent(titleEditText)
                            .addComponent(priceEditText)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addGap(0, 60, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(268, 268, 268))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usunButton)
                        .addGap(29, 29, 29)
                        .addComponent(zwrocButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tytulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(dodajButton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(idEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(titleEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(priceEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addComponent(updateButton)
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usunButton)
                    .addComponent(zwrocButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Panel dostępny tylko dla administratorów");

        javax.swing.GroupLayout dodajTabLayout = new javax.swing.GroupLayout(dodajTab);
        dodajTab.setLayout(dodajTabLayout);
        dodajTabLayout.setHorizontalGroup(
            dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dodajTabLayout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );
        dodajTabLayout.setVerticalGroup(
            dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dodajTabLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );

        tabPanel.addTab("                                           Panel                                                    ", dodajTab);

        nazwaKontaLabel.setText("Nazwa konta:");

        nazwaKontaDB.setText("***");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        twojeRezerwacjeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        twojeRezerwacjeLabel.setText("Twoje Rezerwacje");

        wylogujButton.setText("Wyloguj");
        wylogujButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wylogujButtonMouseClicked(evt);
            }
        });

        odswiezButton.setText("Odśwież");
        odswiezButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odswiezButtonMouseClicked(evt);
            }
        });

        anulujRezButton.setText("Anuluj rezerwację");

        jLabel9.setText("id:");

        twojeRezerwacjeText.setColumns(20);
        twojeRezerwacjeText.setRows(5);
        twojeRezerwacjeText.setEditable(false);
        jScrollPane1.setViewportView(twojeRezerwacjeText);

        javax.swing.GroupLayout kontoTabLayout = new javax.swing.GroupLayout(kontoTab);
        kontoTab.setLayout(kontoTabLayout);
        kontoTabLayout.setHorizontalGroup(
            kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontoTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addComponent(nazwaKontaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nazwaKontaDB))
                    .addComponent(wylogujButton))
                .addGap(142, 142, 142)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kontoTabLayout.createSequentialGroup()
                                .addComponent(odswiezButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(anulujRezButton))))
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(twojeRezerwacjeLabel)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        kontoTabLayout.setVerticalGroup(
            kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontoTabLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addComponent(twojeRezerwacjeLabel)
                        .addGap(18, 18, 18)
                        .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(kontoTabLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(wylogujButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nazwaKontaLabel)
                        .addComponent(nazwaKontaDB))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odswiezButton)
                    .addComponent(anulujRezButton)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        tabPanel.addTab("      Konto       ", kontoTab);

        menuPanel.setVisible(false);

        menuPanel.setLayer(tabPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFieldMouseClicked
        loginField.setText("");        
        loginField.setForeground(Color.BLACK);
    }//GEN-LAST:event_loginFieldMouseClicked

    private void zalogujButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zalogujButtonMouseClicked
        String login = loginField.getText();
        char[] passwordTEMP = passwordField.getPassword();
        String password = new String(passwordTEMP);
        CustomerJpaDao cdao = new CustomerJpaDao();
        Customer session = cdao.findByLogin(login,password);
        if(session==null)
        {
            JOptionPane.showMessageDialog(this,"Niepoprawne dane logowania!","Autentykacja nieudana",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(session.getActive()==true)
                {
                    this.admin=true;
                    jPanel1.setVisible(true);
                }
            idKonta = session.getId();
            nazwaKonta = session.getLogin();
            nazwaKontaDB.setText(nazwaKonta);
            loginPanel.setVisible(false);
            menuPanel.setVisible(true);
        }
        
    }//GEN-LAST:event_zalogujButtonMouseClicked

    private void wylogujButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wylogujButtonMouseClicked
        this.admin=false;
        nazwaKonta=null;
        nazwaKontaDB.setText("***");
        przegladajPanel.removeAll();
        menuPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_wylogujButtonMouseClicked

    private void rejestracjaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejestracjaButtonMouseClicked
        Rejestracja rej = new Rejestracja();
        rej.setTitle("Rejestracja");
        rej.setLocationRelativeTo(null);
        rej.setVisible(true);
        
    }//GEN-LAST:event_rejestracjaButtonMouseClicked

    private void szukajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szukajButtonMouseClicked
        
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        ProductJpaDao pdao = new ProductJpaDao();
        try{
            przegladajPanel.removeAll();
            String szukana = szukajTextField.getText();
            Product product = pdao.findByName(szukana);
            FilmRow.add(panel,product.getTitle(),product.getPrice(),product.getStates(),product.getId());
            przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
            przegladajPanel.add(panel);
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }
        catch(Exception e){
            przegladajPanel.removeAll();
            przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }

    }//GEN-LAST:event_szukajButtonMouseClicked

    private void zalogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujButtonActionPerformed
        
        
    }//GEN-LAST:event_zalogujButtonActionPerformed

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPanelMouseClicked

    private void dodajTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajTabMouseClicked

    }//GEN-LAST:event_dodajTabMouseClicked

    private void dodajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajButtonMouseClicked
        String tytul = tytulTextField.getText();
        String cenaTEMP = cenaTextField.getText();
        double cena = Double.parseDouble(cenaTEMP);
        ProductJpaDao pdao = new ProductJpaDao();
        Product product = new Product();
        product.setTitle(tytul);
        product.setPrice(cena);
        product.setStates("Dostępne");
        pdao.save(product);
        JOptionPane.showMessageDialog(this,"Pomyślnie dodano film.");
    }//GEN-LAST:event_dodajButtonMouseClicked

    private void zobaczWszystkieButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zobaczWszystkieButtonMouseClicked
        przegladajPanel.removeAll();
        przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
        ProductJpaDao pdao = new ProductJpaDao();
        List<Product> emps = pdao.findAllProducts();
        for(int i=0;i<emps.size();i++)
        {
            JPanel panel = new JPanel();
            panel.setLayout(new FlowLayout());
            FilmRow.add(panel,emps.get(i).getTitle(),emps.get(i).getPrice(),emps.get(i).getStates(),emps.get(i).getId());
            przegladajPanel.add(panel);
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }
    }//GEN-LAST:event_zobaczWszystkieButtonMouseClicked

    private void wypozyczButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wypozyczButtonMouseClicked
        try{
            String filmId = idTextField.getText();
            Long id = Long.parseLong(filmId);
            RentalItemJpaDao ridao = new RentalItemJpaDao();
            ProductJpaDao pdao = new ProductJpaDao();
            CustomerJpaDao cdao = new CustomerJpaDao();
            Product product = (Product) pdao.findById(id);
            if(product.getStates().equals("Dostępne"))
            {
                product.setStates("Wypożyczone przez "+nazwaKonta);
                pdao.update(product);
                Customer loggedCustomer = (Customer) cdao.findById(idKonta);
                RentalItem ritem = new RentalItem();
                ritem.setProduct(product);
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date date = new Date();
                ritem.setDate(dateFormat.format(date));
                ritem.setCustomer(loggedCustomer);
                ritem.setFinished("Wypożyczone");
                ridao.save(ritem);
                JOptionPane.showMessageDialog(this,"Pomyślnie wypożyczono film.","Wypożyczenie",JOptionPane.PLAIN_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Produkt nie jest dostępny!","Błąd",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_wypozyczButtonMouseClicked

    private void odswiezButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odswiezButtonMouseClicked
        twojeRezerwacjeText.setText("");    
        RentalItemJpaDao rdao = new RentalItemJpaDao();
        List<RentalItem> emps = rdao.findAllProductsR(idKonta);
        for(int i=0;i<emps.size();i++)
        {
            twojeRezerwacjeText.append("Tytul: "+emps.get(i).getProduct().getTitle()+"\tData transakcji: "+emps.get(i).getDate()+"\tid filmu: "+emps.get(i).getProduct().getId()+"\tStatus: "+emps.get(i).getFinished()+"\n");
        }
            
    }//GEN-LAST:event_odswiezButtonMouseClicked

    private void zarezerwujButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zarezerwujButtonMouseClicked
        try{
            String idTEMP = idRezerText.getText();
            Long id = Long.parseLong(idTEMP);
            String date;
            Calendar cals = Calendar.getInstance();
            SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            formater.format(jXDatePicker.getDate());
            date = formater.format(cals.getTime());
            RentalItemJpaDao ridao = new RentalItemJpaDao();
            ProductJpaDao pdao = new ProductJpaDao();
            CustomerJpaDao cdao = new CustomerJpaDao();
            Product product = (Product) pdao.findById(id);
            if(product.getStates().equals("Dostępne"))
            {
                product.setStates("Zarezerwowane przez " +nazwaKonta);
                pdao.update(product);
                Customer loggedCustomer = (Customer) cdao.findById(idKonta);
                RentalItem ritem = new RentalItem();
                ritem.setProduct(product);
                ritem.setDate(date);
                ritem.setCustomer(loggedCustomer);
                ritem.setFinished("Zarezerwowane");
                ridao.save(ritem);
                JOptionPane.showMessageDialog(this,"Pomyślnie zarezerwowano film.","Rezerwacja",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Produkt nie jest dostępny!","Błąd",JOptionPane.ERROR_MESSAGE);
            }   
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_zarezerwujButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        try{
            String title = titleEditText.getText();
            String idTEMP = idEditText.getText();
            Long id = Long.parseLong(idTEMP);
            String priceTEMP = priceEditText.getText();
            
            
            ProductJpaDao pdao = new ProductJpaDao();
            Product product = (Product) pdao.findById(id);
            if(!title.equals(""))
            {
                product.setTitle(title);
            }
            if(!priceTEMP.equals(""))
            {
                Double price = Double.parseDouble(priceTEMP);
                product.setPrice(price);
            }
            pdao.update(product);
            JOptionPane.showMessageDialog(this,"Pomyślnie zaktualizowano film.","Aktualizacja",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void usunButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usunButtonMouseClicked
        try{
            String idTEMP = idDelete.getText();
            Long id = Long.parseLong(idTEMP);
            ProductJpaDao pdao = new ProductJpaDao();
            Product product = (Product) pdao.findById(id);
            if(product.getStates().equals("Dostępne"))
            {
                pdao.delete(product);
                JOptionPane.showMessageDialog(this,"Pomyślnie usunięto film.","Usuwanie",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Nie można usunąć niedostępnego filmu","Błąd",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_usunButtonMouseClicked

    private void zwrocButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zwrocButtonMouseClicked
        try{
            
            String idTEMP = idDelete.getText();
            Long id = Long.parseLong(idTEMP);
            ProductJpaDao pdao = new ProductJpaDao();
            RentalItemJpaDao rdao = new RentalItemJpaDao();
            Product product = (Product) pdao.findById(id);
            if(!product.getStates().equals("Dostępne"))
            {
                product.setStates("Dostępne");
                List<RentalItem> rentalItemsP = product.getRentalItems();
                RentalItem rent = rentalItemsP.get(rentalItemsP.size()-1);
                rent.setFinished("Zakończone");
                rdao.update(rent);
                pdao.update(product);
                JOptionPane.showMessageDialog(this,"Pomyślnie zwrócono film.","Zwracanie filmu",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Nie można zwrócić dostępnego filmu","Błąd",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_zwrocButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ZalogujSieLabel;
    private javax.swing.JButton anulujRezButton;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JButton dodajButton;
    private javax.swing.JPanel dodajTab;
    private javax.swing.JTextField idDelete;
    private javax.swing.JTextField idEditText;
    private javax.swing.JTextField idRezerText;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker;
    private javax.swing.JPanel kontoTab;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLayeredPane loginPanel;
    private javax.swing.JLayeredPane menuPanel;
    private javax.swing.JLabel nazwaKontaDB;
    private javax.swing.JLabel nazwaKontaLabel;
    private javax.swing.JButton odswiezButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField priceEditText;
    private javax.swing.JPanel przegladajPanel;
    private javax.swing.JScrollPane przegladajScrollPane;
    private javax.swing.JPanel przegladajTab;
    private javax.swing.JButton rejestracjaButton;
    private javax.swing.JButton szukajButton;
    private javax.swing.JTextField szukajTextField;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField titleEditText;
    private javax.swing.JLabel twojeRezerwacjeLabel;
    private javax.swing.JTextArea twojeRezerwacjeText;
    private javax.swing.JTextField tytulTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton usunButton;
    private javax.swing.JButton wylogujButton;
    private javax.swing.JButton wypozyczButton;
    private javax.swing.JButton zalogujButton;
    private javax.swing.JButton zarezerwujButton;
    private javax.swing.JButton zobaczWszystkieButton;
    private javax.swing.JButton zwrocButton;
    // End of variables declaration//GEN-END:variables
}
