/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import org.springframework.stereotype.Component;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jpaDAO.CustomerJpaDao;
import jpaDAO.GenericJpaDao;
import jpaDAO.ProductJpaDao;
import jpaDAO.RentalItemJpaDao;
import jpaDAO.RentalJpaDao;
import models.Customer;
import models.Product;
import models.Rental;
import models.RentalItem;
import wypozyczalniefilmow.FilmRow;


/**
 *
 * @author Rozkurwozaur
 */

@Component
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    private boolean admin;
    private long idKonta;
    private String nazwaKonta;
    public Okno() {
        initComponents();
        this.admin=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dodajPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        loginPanel = new javax.swing.JLayeredPane();
        loginField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        zalogujButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rejestracjaButton = new javax.swing.JButton();
        ZalogujSieLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JLayeredPane();
        tabPanel = new javax.swing.JTabbedPane();
        przegladajTab = new javax.swing.JPanel();
        szukajButton = new javax.swing.JButton();
        przegladajScrollPane = new javax.swing.JScrollPane();
        przegladajPanel = new javax.swing.JPanel();
        szukajTextField = new javax.swing.JTextField();
        zobaczWszystkieButton = new javax.swing.JButton();
        wypozyczButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dodajTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cenaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tytulTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stanTextField = new javax.swing.JTextField();
        dodajButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kontoTab = new javax.swing.JPanel();
        nazwaKontaLabel = new javax.swing.JLabel();
        nazwaKontaDB = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        zmienHasloButton = new javax.swing.JButton();
        twojeRezerwacjeLabel = new javax.swing.JLabel();
        wylogujButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        twojeRezerwacjeText = new javax.swing.JTextPane();
        historiaTranskacjiButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        dodajPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dodajPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajPanelMouseClicked(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout dodajPanelLayout = new javax.swing.GroupLayout(dodajPanel);
        dodajPanel.setLayout(dodajPanelLayout);
        dodajPanelLayout.setHorizontalGroup(
            dodajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajPanelLayout.createSequentialGroup()
                .addGroup(dodajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dodajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(dodajPanelLayout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jLabel2)
                            .addGap(308, 308, 308)))
                    .addGroup(dodajPanelLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jButton2)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        dodajPanelLayout.setVerticalGroup(
            dodajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginField.setForeground(new java.awt.Color(204, 204, 204));
        loginField.setText("Nazwa użytkownika");
        loginField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginFieldMouseClicked(evt);
            }
        });

        loginLabel.setText("Login:");

        passwordLabel.setText("Hasło:");

        zalogujButton.setText("Zaloguj");
        zalogujButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zalogujButtonMouseClicked(evt);
            }
        });
        zalogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nie masz konta? Zarejestruj");

        rejestracjaButton.setText("Rejestracja");
        rejestracjaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejestracjaButtonMouseClicked(evt);
            }
        });

        ZalogujSieLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ZalogujSieLabel.setText("Logowanie");

        loginPanel.setLayer(loginField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(loginLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(zalogujButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(rejestracjaButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginPanel.setLayer(ZalogujSieLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zalogujButton)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(passwordField)))
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(318, 318, 318))))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(ZalogujSieLabel))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(rejestracjaButton)))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(ZalogujSieLabel)
                .addGap(52, 52, 52)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(zalogujButton)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rejestracjaButton)
                .addGap(87, 87, 87))
        );

        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        szukajButton.setText("Szukaj");
        szukajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szukajButtonMouseClicked(evt);
            }
        });

        przegladajScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));

        javax.swing.GroupLayout przegladajPanelLayout = new javax.swing.GroupLayout(przegladajPanel);
        przegladajPanel.setLayout(przegladajPanelLayout);
        przegladajPanelLayout.setHorizontalGroup(
            przegladajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        przegladajPanelLayout.setVerticalGroup(
            przegladajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        przegladajScrollPane.setViewportView(przegladajPanel);

        zobaczWszystkieButton.setText("Zobacz wszystkie");
        zobaczWszystkieButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zobaczWszystkieButtonMouseClicked(evt);
            }
        });

        wypozyczButton.setText("Wypożycz");
        wypozyczButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wypozyczButtonMouseClicked(evt);
            }
        });

        jLabel8.setText("Id:");

        javax.swing.GroupLayout przegladajTabLayout = new javax.swing.GroupLayout(przegladajTab);
        przegladajTab.setLayout(przegladajTabLayout);
        przegladajTabLayout.setHorizontalGroup(
            przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(przegladajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(przegladajTabLayout.createSequentialGroup()
                        .addComponent(zobaczWszystkieButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(szukajButton))
                    .addComponent(przegladajScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, przegladajTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wypozyczButton, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        przegladajTabLayout.setVerticalGroup(
            przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(przegladajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szukajButton)
                    .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zobaczWszystkieButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(przegladajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(przegladajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wypozyczButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        tabPanel.addTab("                                                      Przeglądaj                                                       ", przegladajTab);

        dodajTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajTabMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Dodaj Film");

        jLabel5.setText("Tytuł:");

        jLabel6.setText("Cena:");

        jLabel7.setText("Stan:");

        dodajButton.setText("Dodaj");
        dodajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tytulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dodajButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(203, 203, 203)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tytulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cenaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(stanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(dodajButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Panel dostępny tylko dla administratorów");

        javax.swing.GroupLayout dodajTabLayout = new javax.swing.GroupLayout(dodajTab);
        dodajTab.setLayout(dodajTabLayout);
        dodajTabLayout.setHorizontalGroup(
            dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dodajTabLayout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(258, Short.MAX_VALUE)))
        );
        dodajTabLayout.setVerticalGroup(
            dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dodajTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(dodajTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dodajTabLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );

        tabPanel.addTab("                                            Dodaj                                                    ", dodajTab);

        nazwaKontaLabel.setText("Nazwa konta:");

        nazwaKontaDB.setText("***");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        zmienHasloButton.setText("Zmień hasło");

        twojeRezerwacjeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        twojeRezerwacjeLabel.setText("Twoje Rezerwacje");

        wylogujButton.setText("Wyloguj");
        wylogujButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wylogujButtonMouseClicked(evt);
            }
        });

        twojeRezerwacjeText.setEditable(false);
        jScrollPane2.setViewportView(twojeRezerwacjeText);

        historiaTranskacjiButton.setText("Zobacz historię transakcji");

        jButton1.setText("Anuluj rezerwację");

        javax.swing.GroupLayout kontoTabLayout = new javax.swing.GroupLayout(kontoTab);
        kontoTab.setLayout(kontoTabLayout);
        kontoTabLayout.setHorizontalGroup(
            kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontoTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(nazwaKontaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazwaKontaDB)
                    .addComponent(zmienHasloButton))
                .addGap(71, 71, 71)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(twojeRezerwacjeLabel)
                        .addContainerGap())
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kontoTabLayout.createSequentialGroup()
                                .addComponent(historiaTranskacjiButton)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(kontoTabLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                .addComponent(wylogujButton)
                                .addGap(47, 47, 47))))))
            .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kontoTabLayout.createSequentialGroup()
                    .addGap(692, 692, 692)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        kontoTabLayout.setVerticalGroup(
            kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kontoTabLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addComponent(twojeRezerwacjeLabel)
                        .addGap(18, 18, 18)
                        .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wylogujButton)
                            .addComponent(jScrollPane2)))
                    .addGroup(kontoTabLayout.createSequentialGroup()
                        .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazwaKontaLabel)
                            .addComponent(nazwaKontaDB))
                        .addGap(76, 76, 76)
                        .addComponent(zmienHasloButton))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historiaTranskacjiButton)
                    .addComponent(jButton1))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(kontoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kontoTabLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        tabPanel.addTab("      Konto       ", kontoTab);

        menuPanel.setVisible(false);

        menuPanel.setLayer(tabPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFieldMouseClicked
        loginField.setText("");        
        loginField.setForeground(Color.BLACK);
    }//GEN-LAST:event_loginFieldMouseClicked

    private void zalogujButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zalogujButtonMouseClicked
        String login = loginField.getText();
        char[] passwordTEMP = passwordField.getPassword();
        String password = new String(passwordTEMP);
        CustomerJpaDao cdao = new CustomerJpaDao();
        Customer session = cdao.findByLogin(login,password);
        if(session==null)
        {
            JOptionPane.showMessageDialog(this,"Niepoprawne dane logowania!","Autentykacja nieudana",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(session.getActive()==true)
                {
                    this.admin=true;
                    jPanel1.setVisible(true);
                }
            idKonta = session.getId();
            nazwaKonta = session.getLogin();
            nazwaKontaDB.setText(nazwaKonta);
            loginPanel.setVisible(false);
            menuPanel.setVisible(true);
            System.out.println(idKonta);
        }
        
    }//GEN-LAST:event_zalogujButtonMouseClicked

    private void wylogujButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wylogujButtonMouseClicked
        this.admin=false;
        nazwaKonta=null;
        nazwaKontaDB.setText("***");
        przegladajPanel.removeAll();
        menuPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_wylogujButtonMouseClicked

    private void rejestracjaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejestracjaButtonMouseClicked
        Rejestracja rej = new Rejestracja();
        rej.setTitle("Rejestracja");
        rej.setLocationRelativeTo(null);
        rej.setVisible(true);
        
    }//GEN-LAST:event_rejestracjaButtonMouseClicked

    private void szukajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szukajButtonMouseClicked
        
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        ProductJpaDao pdao = new ProductJpaDao();
        try{
            przegladajPanel.removeAll();
            String szukana = szukajTextField.getText();
            Product product = pdao.findByName(szukana);
            FilmRow.add(panel,product.getTitle(),product.getPrice(),product.getStates(),product.getId());
            przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
            przegladajPanel.add(panel);
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }
        catch(Exception e){
            przegladajPanel.removeAll();
            przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }

    }//GEN-LAST:event_szukajButtonMouseClicked

    private void zalogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujButtonActionPerformed
        
        
    }//GEN-LAST:event_zalogujButtonActionPerformed

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPanelMouseClicked

    private void dodajPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajPanelMouseClicked
        
    }//GEN-LAST:event_dodajPanelMouseClicked

    private void dodajTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajTabMouseClicked

    }//GEN-LAST:event_dodajTabMouseClicked

    private void dodajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajButtonMouseClicked
        String tytul = tytulTextField.getText();
        String cenaTEMP = cenaTextField.getText();
        String stan = stanTextField.getText();
        double cena = Double.parseDouble(cenaTEMP);
        ProductJpaDao pdao = new ProductJpaDao();
        Product product = new Product();
        product.setTitle(tytul);
        product.setPrice(cena);
        product.setStates(stan);
        pdao.save(product);
        JOptionPane.showMessageDialog(this,"Pomyślnie dodano film.");
    }//GEN-LAST:event_dodajButtonMouseClicked

    private void zobaczWszystkieButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zobaczWszystkieButtonMouseClicked
        przegladajPanel.removeAll();
        przegladajPanel.setLayout(new BoxLayout(przegladajPanel,BoxLayout.Y_AXIS));
        ProductJpaDao pdao = new ProductJpaDao();
        List<Product> emps = pdao.findAllProducts();
        for(int i=0;i<emps.size();i++)
        {
            JPanel panel = new JPanel();
            panel.setLayout(new FlowLayout());
            FilmRow.add(panel,emps.get(i).getTitle(),emps.get(i).getPrice(),emps.get(i).getStates(),emps.get(i).getId());
            przegladajPanel.add(panel);
            przegladajPanel.revalidate();
            przegladajPanel.repaint();
        }
    }//GEN-LAST:event_zobaczWszystkieButtonMouseClicked

    private void wypozyczButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wypozyczButtonMouseClicked
        try{
            String filmId = idTextField.getText();
            Long id = Long.parseLong(filmId);
            RentalJpaDao rdao = new RentalJpaDao();
            RentalItemJpaDao ridao = new RentalItemJpaDao();
            ProductJpaDao pdao = new ProductJpaDao();
            CustomerJpaDao cdao = new CustomerJpaDao();
            Product product = (Product) pdao.findById(id);
            Customer loggedCustomer = (Customer) cdao.findById(idKonta);
            RentalItem ritem = new RentalItem();
            ritem.setProduct(product);
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());
            Rental rental = new Rental();
            rental.setDate(timestamp);
            rental.setCustomer(loggedCustomer);
            ritem.setRental(rental);
            rdao.save(rental);
            ridao.save(ritem);
            JOptionPane.showMessageDialog(this,"Pomyślnie wypożyczono film.","Autentykacja nieudana",JOptionPane.PLAIN_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Błąd","Błąd",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_wypozyczButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ZalogujSieLabel;
    private javax.swing.JTextField cenaTextField;
    private javax.swing.JButton dodajButton;
    private javax.swing.JPanel dodajPanel;
    private javax.swing.JPanel dodajTab;
    private javax.swing.JButton historiaTranskacjiButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel kontoTab;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLayeredPane loginPanel;
    private javax.swing.JLayeredPane menuPanel;
    private javax.swing.JLabel nazwaKontaDB;
    private javax.swing.JLabel nazwaKontaLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel przegladajPanel;
    private javax.swing.JScrollPane przegladajScrollPane;
    private javax.swing.JPanel przegladajTab;
    private javax.swing.JButton rejestracjaButton;
    private javax.swing.JTextField stanTextField;
    private javax.swing.JButton szukajButton;
    private javax.swing.JTextField szukajTextField;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel twojeRezerwacjeLabel;
    private javax.swing.JTextPane twojeRezerwacjeText;
    private javax.swing.JTextField tytulTextField;
    private javax.swing.JButton wylogujButton;
    private javax.swing.JButton wypozyczButton;
    private javax.swing.JButton zalogujButton;
    private javax.swing.JButton zmienHasloButton;
    private javax.swing.JButton zobaczWszystkieButton;
    // End of variables declaration//GEN-END:variables
}
